### ISSUE TITLE
Redesign the home page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/network#5]
Adding a wire frame designed by @vinutv 

Please use Tailwindcss for styling.

![WhatsApp Image 2020-03-21 at 2 07 47 AM](https://user-images.githubusercontent.com/14979190/77222902-a44fd200-6b7d-11ea-9f96-5bdf11d3efb1.jpeg)

**Comment by anupamasok** [comment]
@bodhish  WIll Fix This. Please assign it to me.

**Comment by anupamasok** [comment]
Have started working on this issue.

**Comment by krishnapriyatnair** [comment]
can i help in it...? Im familiar with bootstrap css

**Comment by anupamasok** [comment]
@krishnapriyatnair almost done with the changes mentioned above. 
You can certainly polish the UI once I complete my changes and trigger a pull request.

**Comment by madhaven** [comment]
Interested in helping FrontEnd ...

**Comment by anupamasok** [comment]
@krishnapriyatnair @madhaven 
Remaining:
1. Add images/icons for each of the page links under Corona Literacy Mission, Corona Care Center, CoronaSafe Resources and Other Resources
2. Add Tamil Language Link (in Tamil Characters)
3. Under the Mobile view, Fix layout of Langauge options in the Landing. 
Fix text-overflow in cards in smaller layouts
4. Better layout for iPad/Tablet view

**Comment by afeedhshaji** [comment]
Can we get a link to those images as shown inside the boxes of the wireframe design @bodhish

**Comment by madhaven** [comment]
> 1. Add images/icons for each of the page links under Corona Literacy Mission, Corona Care Center, CoronaSafe Resources and Other Resources

All Language links are also available on Top. Should we Repeat it below ?
It looks good and well on top.

**Comment by krishnapriyatnair** [comment]
Ok..Happy to help you at any stage.

**Comment by ghost** [comment]
Hi team, what is the status for this now ??

**Comment by afeedhshaji** [comment]
> Hi team, what is the status for this now ??

PR sent

**Comment by ghost** [comment]
You guys are expecting me to contribute ? If so can I get some tasks?

**Comment by madhaven** [comment]
I believe this issue is completed by now ?
